---
version: '3.8'


services:

  node:
    image: node:19-bullseye-slim
    command: ["index.js"]
    init: true
    restart: always
    working_dir: /app
    volumes:
      - ./target:/app
      - ./node_modules:/app/node_modules
    env_file:
      - ./.env
